### ISSUE TITLE
Impossible to load jwt secret from application.yml

### ISSUE THREAD

**Issue by imseymo** [alvarosanchez/grails-spring-security-rest#382]
I am using the application.yml file to load runtime configurations for the grails-spring-security-rest plugin.

```
grails:
    profile: angularjs
    codegen:
        defaultPackage: telja
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugin.springsecurity:
        conf:
          rest.token.storage.jwt.secret : 'xxxxxxxxxxxxxxxxxxxxxx'
```

However at startup I get this error

> Configuring Spring Security REST 2.0.0.RC1... 2018-07-13 15:04:58.202 ERROR --- [ main] o.s.boot.SpringApplication : Application startup failed
> 
> java.lang.Exception: A JWT secret must be defined. Please provide a value for the config property: grails.plugin.springsecurity.conf.rest.token.storage.jwt.secret
